[package]
name = "onthego-extractor"
version = "0.1.0"
authors = ["Balmath <Balmath@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bson = "0.14.0"
chrono = { version = "0.4", features = ["serde"] }
mongodb = "0.9.0"
serde = "1.0.104"
serde_json = "1.0"
slugify = "0.1.0"
