[package]
name = "onthego-extractor"
version = "0.1.0"
authors = ["Balmath <Balmath@users.noreply.github.com>"]
edition = "2018"

[dependencies]
mongodb = "0.9.0"
bson = "0.14.0"
serde = "1.0.104"
slugify = "0.1.0"

[[bin]]
name = "onthego-extractor"
path = "src/main.rs"

